import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import LoginForm from "@/pages/components/LoginForm/LoginForm";
import {useState} from "react";
import {userData} from "@/custom_types/types";
import ParkingLotList from "@/pages/components/ParkingLotList/ParkingLotList";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [userData,setUserData] = useState<userData | null>(null)

    return (
        <>
          <Head>
            <title>E-Management</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
              {
                  userData == null ?
                  <LoginForm setUserData={setUserData}/>
                      :
                      <ParkingLotList/>
              }

          </main>
        </>
      )
}
